#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac
# Path to the bash it configuration
export BASH_IT="/home/gylstorff/.bash_it"
# Lock and Load a custom theme file.
# Leave empty to disable theming.
# location /.bash_it/themes/
export BASH_IT_THEME='demula'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true
export HISTTIMEFORMAT="%h %d %H:%M:%S "
PROMPT_COMMAND='history -a'
shopt -s histappend
shopt -s cmdhist
export HISTFILESIZE=100000000
export HISTIGNORE="ls:ps:history"
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Uncomment this to make Bash-it create alias reload.
# export BASH_IT_RELOAD_LEGACY=1

# Load Bash It
#source /usr/lib/siemens-proxy/siemens-proxy.sh && proxy_update

# use podman instead docker
export KAS_CONTAINER_ENGINE=podman

function kas-container {
    local KAS_WORK_DIR="$(pwd)/kas_work"
    if [ "${INSIDE_EMACS}" ]; then
        env TERM=linux KAS_WORK_DIR="$KAS_WORK_DIR" ~/bin/kas-container "$@"
    else
        env KAS_WORK_DIR="$KAS_WORK_DIR" ~/bin/kas-container "$@"
    fi
}
function kas-docker {
   kas-container "$@"
}

function ssh {
    if [ "${INSIDE_EMACS}" ]; then
        env TERM=linux /usr/bin/ssh "$@"
    else
        /usr/bin/ssh "$@"
    fi
}


rename() {
    for i in $1*
    do
        mv "$i" "${i/$1/$2}"
    done
}

export UV_USE_IO_URING=0
export SYSTEMD_EDITOR="nvim $@"
export EDITOR="nvim $@"
export DEBEMAIL="quirin.gylstorff@siemens.com"
export KAS_PATH=~/02_repos/kas/
source "$BASH_IT"/bash_it.sh
